# Generated by Django 5.1.6 on 2025-06-26 09:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="awsaccount",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterUniqueTogether(
            name="awsaccount",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="awsaccount",
            name="account_id",
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="awsaccount",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="awsaccount",
            name="invitation_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="awsaccount",
            name="name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="awsaccount",
            name="invitation_status",
            field=models.CharField(
                choices=[
                    ("REQUESTED", "Requested"),
                    ("OPEN", "Open"),
                    ("CANCELED", "Canceled"),
                    ("ACCEPTED", "Accepted"),
                    ("DECLINED", "Declined"),
                    ("EXPIRED", "Expired"),
                ],
                default="REQUESTED",
                max_length=30,
            ),
        ),
        migrations.RemoveField(
            model_name="awsaccount",
            name="aws_mail",
        ),
        migrations.RemoveField(
            model_name="awsaccount",
            name="invitation",
        ),
        migrations.RemoveField(
            model_name="awsaccount",
            name="partner",
        ),
    ]
