# Generated by Django 5.1.6 on 2025-06-26 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_alter_awsaccount_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="awsaccount",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="awsaccount",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="aws_accounts",
                to="main.customer",
            ),
        ),
        migrations.AlterField(
            model_name="awsaccount",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
