# Generated by Django 5.1.6 on 2025-06-26 06:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_user_is_staff_alter_user_is_superuser"),
    ]

    operations = [
        migrations.CreateModel(
            name="RootInvoice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.UUIDField(blank=True, null=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("update_history", models.JSONField(blank=True, null=True)),
                (
                    "invoice_file",
                    models.FileField(blank=True, null=True, upload_to="invoice/"),
                ),
                ("invoice_date", models.DateField()),
                ("bill_start_date", models.DateField()),
                ("bill_end_date", models.DateField()),
            ],
            options={
                "verbose_name": "Root Invoice",
                "verbose_name_plural": "Root Invoices",
            },
        ),
        migrations.CreateModel(
            name="AWSAccountInvoice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.UUIDField(blank=True, null=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("update_history", models.JSONField(blank=True, null=True)),
                ("total_ammount", models.FloatField(default=0.0)),
                ("invoice_date", models.DateField()),
                ("bill_start_date", models.DateField()),
                ("bill_end_date", models.DateField()),
                (
                    "aws_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aws_account_invoices",
                        to="main.awsaccount",
                    ),
                ),
            ],
            options={
                "verbose_name": "AWS Account Invoice",
                "verbose_name_plural": "AWS Account Invoices",
            },
        ),
        migrations.CreateModel(
            name="AwsCostManagement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.UUIDField(blank=True, null=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("update_history", models.JSONField(blank=True, null=True)),
                ("billing_date", models.DateField()),
                ("account_id", models.CharField(max_length=255)),
                (
                    "account_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "account_email",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("service", models.CharField(max_length=255)),
                ("cost", models.FloatField(default=0)),
                ("cost_unit", models.CharField(max_length=25)),
                ("usage", models.FloatField(default=0)),
                ("usage_unit", models.CharField(default="-", max_length=25)),
                (
                    "aws_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.awsaccount",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cost Management",
                "verbose_name_plural": "Cost Managements",
            },
        ),
        migrations.CreateModel(
            name="MonthlyCostByAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.UUIDField(blank=True, null=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("update_history", models.JSONField(blank=True, null=True)),
                ("month", models.DateField()),
                ("total_cost", models.FloatField(default=0)),
                (
                    "aws_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monthly_cost_by_account",
                        to="main.awsaccount",
                    ),
                ),
            ],
            options={
                "verbose_name": "Monthly Cost by Account",
                "verbose_name_plural": "Monthly Costs by Account",
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.UUIDField(blank=True, null=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("update_history", models.JSONField(blank=True, null=True)),
                ("name", models.CharField(max_length=50)),
                (
                    "region",
                    models.CharField(
                        blank=True, default="us-east-1", max_length=50, null=True
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "AWS Service",
                "verbose_name_plural": "AWS Services",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("name", "region"), name="unique_service_region"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AccountService",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.UUIDField(blank=True, null=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("update_history", models.JSONField(blank=True, null=True)),
                ("blended_cost", models.FloatField(default=0)),
                ("usage_amount", models.FloatField(default=0)),
                ("unblendend_cost", models.FloatField(default=0)),
                ("usage_start_date", models.DateField(blank=True, null=True)),
                ("usage_end_date", models.DateField(blank=True, null=True)),
                ("product_description", models.TextField(blank=True, null=True)),
                ("tax_type", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "line_item_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "product_code",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "currency_code",
                    models.CharField(
                        blank=True, default="USD", max_length=10, null=True
                    ),
                ),
                ("public_on_demand_cost_pricing", models.FloatField(default=0)),
                (
                    "usage_unit_pricing",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "usage_term_pricing",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("public_on_demand_rate_pricing", models.FloatField(default=0)),
                ("savings_plan_used_commitment", models.FloatField(default=0)),
                ("savings_plan_savings_plan_rate", models.FloatField(default=0)),
                ("savings_plan_total_commitment_to_date", models.FloatField(default=0)),
                (
                    "savings_plan_savings_plan_effective_cost",
                    models.FloatField(default=0),
                ),
                (
                    "savings_plan_savings_plan_arn",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "savings_plan_recurring_commitment_for_billing_period",
                    models.FloatField(default=0),
                ),
                (
                    "savings_plan_amortized_upfront_commitment_for_billing_period",
                    models.FloatField(default=0),
                ),
                (
                    "extra_rate_type",
                    models.CharField(
                        choices=[("Flat", "Flat"), ("Percentage", "Percentage")],
                        default="Percentage",
                        max_length=50,
                    ),
                ),
                ("extra_rate_value", models.FloatField(default=0)),
                (
                    "aws_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="account_services",
                        to="main.awsaccount",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.rootinvoice",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="account_services",
                        to="main.service",
                    ),
                ),
            ],
            options={
                "verbose_name": "Account Service",
                "verbose_name_plural": "Account Services",
                "indexes": [
                    models.Index(
                        fields=["aws_account", "invoice"],
                        name="main_accoun_aws_acc_f42c16_idx",
                    ),
                    models.Index(
                        fields=["usage_end_date"], name="main_accoun_usage_e_351922_idx"
                    ),
                ],
            },
        ),
    ]
