# Generated by Django 5.1.6 on 2025-06-26 10:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_alter_awsaccount_group"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="provider_name",
        ),
        migrations.RemoveField(
            model_name="partner",
            name="aws_access_key_id",
        ),
        migrations.RemoveField(
            model_name="partner",
            name="aws_secret_access_key",
        ),
    ]
