# Generated by Django 5.1.6 on 2025-06-26 10:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_remove_customer_provider_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="business_id",
            field=models.CharField(default=uuid.uuid4, max_length=100, unique=True),
        ),
    ]
